brew install abseil
brew install ack
brew install aom
brew install apache-arrow
brew install assimp
brew install augeas
brew install autoconf
brew install automake
brew install awscli@1
brew install bash
brew install bdw-gc
brew install berkeley-db
brew install boost
brew install brotli
brew install c-ares
brew install cabal-install
brew install cairo
brew install ceres-solver
brew install certbot
brew install cloc
brew install cmake
brew install composer
brew install coreutils
brew install ctags
brew install curl
brew install dav1d
brew install dbus
brew install dialog
brew install direnv
brew install docbook
brew install docbook-xsl
brew install dos2unix
brew install double-conversion
brew install dvc
brew install eigen
brew install elixir
brew install entr
brew install erlang
brew install exiftool
brew install ffmpeg
brew install flac
brew install fontconfig
brew install freetype
brew install frei0r
brew install fribidi
brew install gcc
brew install gd
brew install gdbm
brew install gdk-pixbuf
brew install gettext
brew install gflags
brew install ghc
brew install ghostscript
brew install giflib
brew install git
brew install git-gui
brew install gl2ps
brew install glew
brew install glib
brew install glog
brew install gmp
brew install gnu-getopt
brew install gnu-sed
brew install gnu-tar
brew install gnutls
brew install gobject-introspection
brew install graphicsmagick
brew install graphite2
brew install graphviz
brew install grpc
brew install gts
brew install guile
brew install harfbuzz
brew install hdf5
brew install helm
brew install heroku
brew install heroku-node
brew install htop
brew install htop-osx
brew install httpie
brew install hub
brew install icu4c
brew install ilmbase
brew install imagemagick
brew install isl
brew install jansson
brew install jasper
brew install jemalloc
brew install jpeg
brew install jq
brew install jsoncpp
brew install kompose
brew install krb5
brew install kubernetes-helm
brew install lame
brew install ldns
brew install leptonica
brew install libass
brew install libb2
brew install libbluray
brew install libcbor
brew install libde265
brew install libev
brew install libevent
brew install libffi
brew install libfido2
brew install libgcrypt
brew install libgit2
brew install libgpg-error
brew install libheif
brew install libidn2
brew install liblqr
brew install libmetalink
brew install libmpc
brew install libogg
brew install libomp
brew install libpng
brew install libproxy
brew install libpthread-stubs
brew install librsvg
brew install libsamplerate
brew install libsndfile
brew install libsodium
brew install libsoxr
brew install libssh2
brew install libtasn1
brew install libtiff
brew install libtool
brew install libunistring
brew install libuv
brew install libvidstab
brew install libvorbis
brew install libvpx
brew install libx11
brew install libxau
brew install libxcb
brew install libxdmcp
brew install libxext
brew install libxml2
brew install libxrender
brew install libxslt
brew install libyaml
brew install little-cms2
brew install lua
brew install lz4
brew install lzo
brew install m4
brew install mas
brew install md5sha1sum
brew install metis
brew install mkcert
brew install mpdecimal
brew install mpfr
brew install mysql
brew install ncdu
brew install ncurses
brew install netcdf
brew install netpbm
brew install nettle
brew install nghttp2
brew install node
brew install node@10
brew install nspr
brew install nss
brew install numpy
brew install oniguruma
brew install openblas
brew install opencore-amr
brew install opencv
brew install openexr
brew install openjdk
brew install openjpeg
brew install openldap
brew install openssh
brew install openssl@1.1
brew install opus
brew install p11-kit
brew install pandoc
brew install pango
brew install pcre
brew install pcre2
brew install perl
brew install pixman
brew install pkg-config
brew install poppler
brew install postgresql
brew install protobuf
brew install pugixml
brew install pyenv
brew install pyqt
brew install pyqt@5
brew install python
brew install python-tabulate
brew install python3
brew install python@2
brew install python@3.7
brew install python@3.8
brew install python@3.9
brew install qt
brew install qt@5
brew install rapidjson
brew install rav1e
brew install rbenv
brew install rcm
brew install re2
brew install readline
brew install reattach-to-user-namespace
brew install redis
brew install rtmpdump
brew install rubberband
brew install ruby
brew install ruby-build
brew install sdl2
brew install shared-mime-info
brew install sip
brew install snappy
brew install speex
brew install sphinx-doc
brew install sqlite
brew install srt
brew install suite-sparse
brew install szip
brew install tbb
brew install tcl-tk
brew install terraform
brew install terraform@0.12
brew install tesseract
brew install tesseract-lang
brew install the_silver_searcher
brew install theora
brew install thrift
brew install tig
brew install tmux
brew install trash
brew install tree
brew install unbound
brew install utf8cpp
brew install utf8proc
brew install v8
brew install vim
brew install vtk
brew install watch
brew install webp
brew install wget
brew install wxmac
brew install x264
brew install x265
brew install xmlto
brew install xorgproto
brew install xvid
brew install xz
brew install yarn
brew install zeromq
brew install zimg
brew install zsh
brew install zstd
